### ISSUE TITLE
Prevent invalid XML output

### ISSUE THREAD

**Issue by nichtich** [Blacksmoke16/oq#9] opened 2019-07-15 07:30 UTC
I think this is not intended:

~~~
echo '{ "a b=\"c\"": {} }' | oq -o xml .
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <a b="c"/>
</root>
~~~

Disallowed XML element and attribute names should result in a error. The format to check against is [defined here](https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-Name) and [discussed here](https://stackoverflow.com/questions/3158274/what-would-be-a-regex-for-valid-xml-names). Note that names starting with `xml:` should also be allowed.

**Comment by Blacksmoke16** [comment] 2019-07-15 12:30
Sorry if im missing something here, but isn't that valid XML?  I ran it through some linters and didn't get any errors.  However, based on the link you provided I think 

```bash
echo '{ "1 b=\"c\"": {} }' | ./bin/oq -o xml .
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <1 b="c"/>
</root>
```

should error since a number is not a valid start character.

**Comment by nichtich** [comment] 2019-07-15 13:59
~~~
echo '{ "a b=\"c\"": "" }' | oq -o xml .
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <a b="c"></a b="c">
</root>
~~~

**Comment by Blacksmoke16** [comment] 2019-07-15 17:36
@nichtich This is actually an issue in Crystal stdlib, I create https://github.com/crystal-lang/crystal/issues/7963 to deal with it and will have a PR for it soon.

In that case there is nothing to do in `oq` itself, and will just start working as intended after its merged and the next version of Crystal is released.

**Comment by Blacksmoke16** [comment] 2019-07-15 17:40
Er, I'll keep this open until its fixed on Crystal's end.

**Closed** 2019-07-17 12:11 UTC
Labels: format:xml, kind:bug
